### PR TITLE
Add coordinate sanitizer

### PR DESCRIPTION
**Pull request by iamfrank**
Enable parsing lat/lon or x/y coordinates from URL params - both for WGS84 and EPSG:25832 formats.

### CODE REVIEW

**Comment by rasmustoender** [comment]
Issues still present. 

Example: http://localhost:8000/viewer.html?lat=55.692077&lon=12.569484&orientation=north&item=2021_82_23_2_0017_00006005_10cm&center=724334.7885496999%2C6177584.701484572

**Review by rasmustoender — CHANGES_REQUESTED** [review]
Issues still present

**Comment by iamfrank** [comment]
The example URL contains both item and coordinate values that don't fit each other. The system prioritizes the item and displays its corresponding image.

I believe it to be an unlikely case, since users will not know the item when requesting a view with coordinates.
A better example could be localhost:8000/viewer.html?lat=55.692077&lon=12.569484

**Review by rasmustoender — APPROVED** [review]
Looks good

**Pull request merged**
